## Ex1 Use data from Danmarks Statistik - Databanken
1. Go to https://www.dst.dk/da/Statistik/brug-statistikken/muligheder-i-statistikbanken/api#testkonsol
2. Open 'Konsol' and click 'Start Konsol'
3. In the console at pt 1: choose 'Retrieve tables', pt 2: choose get request and json format and pt 3: execute:
  1. check the result
  2. in the code below this same get request is used to get information about all available data tables in 'databanken'. 
4. Change pt. 1 in the console to 'Retrieve data', pt 2: 'get request' and Table id: 'FOLK1A', format: csv, delimiter: semicolon and click: 'Variable and value codes' and choose some sub categories (Hint: hover over the codes to see their meaning). Finally execute and see what data you get.
5. With data aggregation and data visualization answer the following questions:
  1. What is the change in pct of divorced danes from 2008 to 2020?
  2. Which of the 5 biggest cities has the highest percentage of 'Never Married' in 2020?
  3. Show a bar chart of changes in marrital status in Copenhagen from 2008 till now
  4. Show 2 plots in same figure: 'Married' and 'Never Married' for all ages in DK in 2020 (Hint: x axis is age from 0-125, y axis is how many people in the 2 categories). Add lengend to show names on graphs
  
## Ex2 Use another table (extra)
Choose any of the other tables in 'databanken' to find interesting data.
1. Collect the data
2. Pose 5 or more interesing questions to the data
3. Answer the questions by aggregating the data
4. Illustrate the answers with visual plots

In [1]:
import pandas as pd 
url = 'https://api.statbank.dk/v1/tables'
dst = pd.read_json(url)
dst.to_csv('dk-stat-all-tables.csv', encoding='utf-8', index=False)
dst[:20]

,id,text,unit,updated,firstPeriod,latestPeriod,active,variables
0,FOLK1A,Folketal den 1. i kvartalet,antal,2020-08-11T08:00:00,2008K1,2020K3,True,"[område, køn, alder, civilstand, tid]"
1,FOLK1B,Folketal den 1. i kvartalet,antal,2020-08-11T08:00:00,2008K1,2020K3,True,"[område, køn, alder, statsborgerskab, tid]"
2,FOLK1C,Folketal den 1. i kvartalet,antal,2020-08-11T08:00:00,2008K1,2020K3,True,"[område, køn, alder, herkomst, oprindelsesland..."
3,FOLK1D,Folketal den 1. i kvartalet,antal,2020-08-11T08:00:00,2008K1,2020K3,True,"[område, køn, alder, statsborgerskab, tid]"
4,FOLK1E,Folketal den 1. i kvartalet,antal,2020-08-11T08:00:00,2008K1,2020K3,True,"[område, køn, alder, herkomst, tid]"
5,FOLK2,Folketal 1. januar,antal,2020-02-11T08:00:00,1980,2020,True,"[alder, køn, herkomst, statsborgerskab, oprind..."
6,FOLK3,Folketal 1. januar,antal,2020-02-11T08:00:00,2008,2020,True,"[fødselsdag, fødselsmåned, fødselsår, tid]"
7,FT,Folketal (summariske tal fra folketællinger),antal,2020-02-11T08:00:00,1769,2020,True,"[hovedlandsdele, tid]"
8,BEF5F,Personer født på Færøerne og bosat i Danmark 1...,antal,2020-02-11T08:00:00,2008,2020,True,"[køn, alder, forældrenes fødested, tid]"
9,BEF5G,Personer født i Grønland og bosat i Danmark 1....,antal,2020-02-11T08:00:00,2008,2020,True,"[køn, alder, forældrenes fødested, tid]"
10,BEF5,Folketal pr. 1. januar,antal,2020-02-11T08:00:00,1990,2020,True,"[køn, alder, fødeland, tid]"
11,BY3,Folketal 1. januar,-,2020-06-11T08:00:00,2017,2020,True,"[byområder og landdistrikter, folketal, areal ..."
12,BY1,Folketal 1. januar,antal,2020-04-29T08:00:00,2010,2020,True,"[byområder og landdistrikter, alder, køn, tid]"
13,BY4,Husstande 1. januar,antal,2020-04-29T08:00:00,2010,2020,True,"[byområder og landdistrikter, husstandstype, a..."
14,BY2,Folketal 1. januar,antal,2020-04-29T08:00:00,2010,2020,True,"[kommune, bystørrelse, alder, køn, tid]"
15,BEF4,Folketal 1. januar,antal,2020-04-01T08:00:00,1901,2020,True,"[øer, tid]"
16,HISB3,Nøgletal om befolkningen,antal,2020-02-13T08:00:00,1901,2020,True,"[bevægelsesart, tid]"
17,BEV22,Befolkningens udvikling (foreløbig opgørelse),antal,2020-08-11T08:00:00,2007K2,2020K2,True,"[område, bevægelsesart, køn, tid]"
18,BEV107,Befolkningens udvikling,antal,2020-02-11T08:00:00,2006,2019,True,"[område, bevægelsesart, køn, tid]"
19,GALDER,Gennemsnitsalder,gns.,2020-02-11T08:00:00,2005,2020,True,"[kommune, køn, tid]"

A)

In [2]:
data2008And2020 = pd.read_csv('https://api.statbank.dk/v1/data/FOLK1A/CSV?delimiter=Semicolon&CIVILSTAND=F&OMR%C3%85DE=000&K%C3%98N=TOT&Tid=2020K3%2C2008K4', sep=';')
print(data2008And2020)
d2008 = data2008And2020.iloc[0,4]
d2020 = data2008And2020.iloc[1,4]
result = round(((d2020/d2008)-1)*100,2)
print('Change in percent between 2008 and 2020 is: ' + str(result))

  CIVILSTAND       OMRÅDE    KØN     TID  INDHOLD
0   Fraskilt  Hele landet  I alt  2008K4   432156
1   Fraskilt  Hele landet  I alt  2020K3   550715
Change in percent between 2008 and 2020 is: 27.43

B)

In [3]:
result = round(((d2020/d2008)-1)*100,2)
print('change in percent between 2008 and 2020 is: ' + str(result))

change in percent between 2008 and 2020 is: 27.43

In [4]:
dataOpgB = pd.read_csv('https://api.statbank.dk/v1/data/FOLK1A/CSV?delimiter=Semicolon&CIVILSTAND=TOT&Tid=2020K3&K%C3%98N=TOT&OMR%C3%85DE=*', sep=';')
alldata = dataOpgB.sort_values(by=['INDHOLD'],ascending = False)
citydata = alldata[alldata.OMRÅDE.str.contains('Region')==False]
citydata = citydata[citydata.OMRÅDE.str.contains('Hele landet')==False] [:5]
print(citydata)

    CIVILSTAND     TID    KØN     OMRÅDE  INDHOLD
2        I alt  2020K3  I alt  København   633035
84       I alt  2020K3  I alt     Aarhus   349433
104      I alt  2020K3  I alt    Aalborg   217316
58       I alt  2020K3  I alt     Odense   204718
71       I alt  2020K3  I alt      Vejle   116468

In [38]:
unmarrieddata = pd.read_csv('https://api.statbank.dk/v1/data/FOLK1A/CSV?delimiter=Semicolon&OMR%C3%85DE=*&K%C3%98N=TOT&CIVILSTAND=U&Tid=2020K3', sep=';')
Ualldata = unmarrieddata.sort_values(by=['INDHOLD'],ascending = False)
Ucitydata = Ualldata[Ualldata.OMRÅDE.str.contains('Region')==False]
Ucitydata = Ucitydata[Ucitydata.OMRÅDE.str.contains('Hele landet')==False] [:10]



fivebig = []
for i in range(5) :
    fivebig.append([citydata.iloc[i,3], citydata.iloc[i,4] ])


liste = []
resultProcent = 0 
resultCity =""
for i in fivebig:
    city = i 
   # print(city)
    a = int(Ucitydata[Ucitydata[:]["OMRÅDE"] == (city[0])]["INDHOLD"])
  
    #print(city)
    result = round(((a/city[1]))*100,2)
    city.append(result)
    print(city)
    liste.append(result)

['København', 633035, 65.43]
['Aarhus', 349433, 59.66]
['Aalborg', 217316, 54.62]
['Odense', 204718, 55.04]
['Vejle', 116468, 47.36]